name: (Deprecated) Use was-pipeline.yml / web-pipeline.yml / frontend-deploy.yml

on:
  workflow_dispatch:

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow has been split into separate files."
